### ISSUE TITLE
Przemieszczanie się przez klienta za pomocą zmiany wektora prędkości

### ISSUE THREAD

**Issue by MichalNiesyto** [Caier/PRprojekt#1]
Obecny protokół (moja wersja) zapewnia możliwość przesłania nowej pozycji przez klienta co jakiś czas. 
Problem z tym jest taki, że klient generuje dość dużą liczbę niepotrzebnych operacji RPC aby to zrobić i są na to lepsze sposoby.

Proponuję dodanie wiadomości, która ustawiałaby wektor prędkości i ewentualnie wektor przyspieszenia. W ten sposób to serwer jest w stanie poruszać wieloma komórkami w szybki sposób, ale to klient staje się odpowiedzialny za logikę poruszania - wartości wektora mają mieć znaczenie.

To oczywiście usuwa koncepcję szybkości jako wartości jednowymiarowej z komórek i wprowadza to w sposób wektorowy, który daje możliwość podania również kierunku.

**Comment by Caier** [comment]
popieram pomysł jednak jakoś i tak nie ufam że klient będzie sam sobie mógł obliczać pozycję - myślę że się rozsynchronizują. ale jeśli tak się stanie to po prostu można zmienić strategię i sprawić że serwer przesyła w odpowiedzi aktualną pozycję komórki, albo nawet samo rpc które zwraca pozycję.

**Comment by MichalNiesyto** [comment]
Nie będzie pełnej możliwości, ale chodzi raczej o możliwość przybliżonego wyliczania przez jakiś czas, dodatkowo wartości mają być mnożone przez czas jaki upłynął od poprzedniej ramki (logiczne dla UI), a tutaj może np. robić sleep, ale koncepcja ogólnie ma pozwolić na minimalizację RPC przy zachowaniu logiki po stronie klienta

**Comment by MichalNiesyto** [comment]
Ale ogólnie zamiast zmiany pozycji dodanie do protokołu dwóch rzeczy:

1. Zmiana prędkości (ewentualnie przyspieszenia)
2. Poznanie pozycji

I tak nigdy nie będą mieć dokładnie takich samych wartości. To w sumie jest problemem w systemach rozproszonych, nawet jakby ustawić stałe FPS i stały czas co ile one się przesuwają, to zawsze będzie jakaś nieścisłość w pozycji. Chodzi o to, że ta pozycja to float i używamy przybliżeń. Co jakiś czas klient może poprosić o swoją pozycję, ale ogólnie nigdy nie będą w pełni zsynchronizowane.
